### ISSUE TITLE
Test failure only on windows (testGetMergedBundleMap_requiredFeatureWithNoVersion)

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde.ui#20]
org.eclipse.pde.ui.tests.launcher.FeatureBasedLaunchTest | testGetMergedBundleMap_requiredFeatureWithNoVersion | Error | element cannot be mapped to a null key                                                                           java.lang.NullPointerException: element cannot be mapped to a null key                                                  	at java.base/java.util.Objects.requireNonNull(Objects.java:246)                                                  	at java.base/java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1127)                                                  	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)                                                  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)                                                  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)                                                  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)                                                  	at java.base/java.uti
-- | -- | -- | --

**Comment by vik-chand** [comment]
This could be intermittent.

**Comment by EclipseNewb** [comment]
could not reproduce locally on windows

**Comment by jukzi** [comment]
happend again https://download.eclipse.org/eclipse/downloads/drops4/I20250220-0450/testresults/html/org.eclipse.pde.ui.tests_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

```
java.lang.NullPointerException: element cannot be mapped to a null key
at java.base/java.util.Objects.requireNonNull(Objects.java:259)
at java.base/java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1105)
at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getPrioritizedAvailableFeatures(BundleLauncherHelper.java:312)
at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getSelectedFeatures(BundleLauncherHelper.java:254)
at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getMergedBundleMapFeatureBased(BundleLauncherHelper.java:186)
at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getMergedBundleMap(BundleLauncherHelper.java:141)
at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getMergedBundleMap(BundleLauncherHelper.java:108)
at org.eclipse.pde.ui.tests.launcher.FeatureBasedLaunchTest.assertGetMergedBundleMap(FeatureBasedLaunchTest.java:1448)
at org.eclipse.pde.ui.tests.launcher.FeatureBasedLaunchTest.assertGetMergedBundleMap(FeatureBasedLaunchTest.java:1433)
at org.eclipse.pde.ui.tests.launcher.FeatureBasedLaunchTest.testGetMergedBundleMap_includedFeatureWithSpecificVersion(FeatureBasedLaunchTest.java:521)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:267)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:267)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:267)

```
